version: '3'

services:
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: requirements/nginx/Dockerfile
    depends_on:
      - wordpress
    ports:
      - "443:443"
    networks:
      - inception
    volumes:
      - ./requirements/nginx/conf/:/etc/nginx/http.d/
      - ./requirements/nginx/tools:/etc/nginx/ssl/
      - wp-volume:/var/www/
    restart: always

  mariadb:
    container_name: mariadb
    build:
      context: .
      dockerfile: requirements/mariadb/Dockerfile
      args:
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASS: ${DB_PASS}
        DB_ROOT: ${DB_ROOT}
    ports:
      - "3306:3306"
    networks:
      - inception
    volumes:
      - db-volume:/var/lib/mysql
    restart: always

  wordpress:
    container_name: wordpress
    build:
      context: .
      dockerfile: requirements/wordpress/Dockerfile
      args:
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASS: ${DB_PASS}
    depends_on:
      - mariadb
    networks:
      - inception
    volumes:
      - wp-volume:/var/www/
    restart: always

  redis:
    container_name: redis
    build:
      context: .
      dockerfile: requirements/bonus/redis/Dockerfile
    depends_on:
      - wordpress
    ports:
      - "6379:6379"
    networks:
      - inception
    restart: always

  vsftpd:
    container_name: vsftpd
    build:
      context: .
      dockerfile: requirements/bonus/vsftpd/Dockerfile
      args:
        FTP_USR: ${FTP_USR}
        FTP_PWD: ${FTP_PWD}
    depends_on:
      - wordpress
    ports:
      - "21:21"
    volumes:
      - wp-volume:/var/www/
    networks:
     - inception
    restart: always

  adminer:
    container_name: adminer
    build:
      context: .
      dockerfile: requirements/bonus/adminer/Dockerfile
    depends_on:
      - mariadb
    ports:
      - "8080:8080"
    networks:
     - inception
    restart: always

  website:
    container_name: website
    build:
      context: .
      dockerfile: requirements/bonus/website/Dockerfile
    ports:
      - "80:80"
    restart: always

#  portainer:
#   container_name: portainer
#   image: portainer-ce:2.11.1
#    ports:
#      - "8000:8000"
#      - "9443:9443"
#    volumes: 
3      - /var/run/docker.sock:/var/run/docker.sock
#      - portainer_data:/data
#    restart: always

volumes:
  wp-volume:
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/data/wordpress

  db-volume:
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/data/mariadb

networks:
    inception:
        driver: bridge
